image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-gateway-registry:
  stage: build
  script:
    gradle gateway:registry:assemble gateway:registry:testClasses

checkStyle-gateway-registry:
  needs:
    - build-gateway-registry
  stage: staticAnalysis
  script:
    gradle gateway:registry:checkstyleMain gateway:registry:checkStyleTest
  allow_failure: true


PMD-gateway-registry:
  needs:
    - build-gateway-registry
  stage: staticAnalysis
  script:
    gradle gateway:registry:pmdMain
  allow_failure: true
