# Port of the microservice
server:
  port: 8080

spring:
  application:
    name: ROUTER-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

security:
  internal-ranges:
    - start: 10.0.0.0
      end: 10.255.255.255
    - start: 127.16.0.0
      end: 127.31.255.255
    - start: 192.168.0.0
      end: 192.168.255.255
    - start: 127.0.0.0
      end: 127.255.255.255
