image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-notification-microservice:
  stage: build
  script:
    gradle notification:microservice:assemble notification:microservice:testClasses

checkStyle-notification-microservice:
  needs:
    - build-notification-microservice
  stage: staticAnalysis
  script:
    gradle notification:microservice:checkstyleMain notification:microservice:checkStyleTest
  allow_failure: true


PMD-notification-microservice:
  needs:
    - build-notification-microservice
  stage: staticAnalysis
  script:
    gradle notification:microservice:pmdMain
  allow_failure: true

test-notification-microservice:
  needs:
    - build-notification-microservice
  stage: test
  script:
    - gradle notification:microservice:test notification:microservice:jacocoTestReport
    - cat notification/microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
