image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-contract-microservice:
  stage: build
  script:
    gradle contract:microservice:assemble contract:microservice:testClasses

checkStyle-contract-microservice:
  needs:
    - build-contract-microservice
  stage: staticAnalysis
  script:
    gradle contract:microservice:checkstyleMain contract:microservice:checkStyleTest
  allow_failure: true


PMD-contract-microservice:
  needs:
    - build-contract-microservice
  stage: staticAnalysis
  script:
    gradle contract:microservice:pmdMain
  allow_failure: true

test-contract-microservice:
  needs:
    - build-contract-microservice
  stage: test
  script:
    - gradle contract:microservice:test contract:microservice:jacocoTestReport
    - cat contract/microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
