image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-notification-client:
  stage: build
  script:
    gradle notification:client:assemble notification:client:testClasses

checkStyle-notification-client:
  needs:
    - build-notification-microservice
  stage: staticAnalysis
  script:
    gradle notification:client:checkstyleMain notification:client:checkStyleTest
  allow_failure: true


PMD-notification-client:
  needs:
    - build-notification-client
  stage: staticAnalysis
  script:
    gradle notification:client:pmdMain
  allow_failure: true

test-notification-client:
  needs:
    - build-notification-client
  stage: test
  script:
    - gradle notification:client:test notification:client:jacocoTestReport
    - cat notification/client/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
