image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-request-client:
  stage: build
  script:
    gradle request:client:assemble request:client:testClasses

checkStyle-request-client:
  needs:
    - build-request-microservice
  stage: staticAnalysis
  script:
    gradle request:client:checkstyleMain request:client:checkStyleTest
  allow_failure: true


PMD-request-client:
  needs:
    - build-request-client
  stage: staticAnalysis
  script:
    gradle request:client:pmdMain
  allow_failure: true

test-request-client:
  needs:
    - build-request-client
  stage: test
  script:
    - gradle request:client:test request:client:jacocoTestReport
    - cat request/client/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
