spring:
  datasource:
    url: jdbc:h2:./authentication-microservice/sem_authentication;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    enabled: true
