# Port of the microservice
server:
  port: 8081

# Secret for the JWT signing
jwt:
  secret: T2hJKTHD4D+59wwX3WG28cOD7o1haIHgYY2HaIv7XZE46bWvRDfnZBDHfSzGaDAcF/XZ+B42f2rpUE9uISN5ag==

springdoc:
  swagger-ui:
    enabled: false

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:./authentication-microservice/sem_authentication;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect