image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-request-microservice:
  stage: build
  script:
    gradle request:microservice:assemble request:microservice:testClasses

checkStyle-request-microservice:
  needs:
    - build-request-microservice
  stage: staticAnalysis
  script:
    gradle request:microservice:checkstyleMain request:microservice:checkStyleTest
  allow_failure: true


PMD-request-microservice:
  needs:
    - build-request-microservice
  stage: staticAnalysis
  script:
    gradle request:microservice:pmdMain
  allow_failure: true

test-request-microservice:
  needs:
    - build-request-microservice
  stage: test
  script:
    - gradle request:microservice:test request:microservice:jacocoTestReport
    - cat request/microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
