image: gradle:7-jdk11-focal

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-gateway-router:
  stage: build
  script:
    gradle gateway:router:assemble gateway:router:testClasses

checkStyle-gateway-router:
  needs:
    - build-gateway-router
  stage: staticAnalysis
  script:
    gradle gateway:router:checkstyleMain gateway:router:checkStyleTest
  allow_failure: true


PMD-gateway-router:
  needs:
    - build-gateway-router
  stage: staticAnalysis
  script:
    gradle gateway:router:pmdMain
  allow_failure: true

test-gateway-router:
  needs:
    - build-gateway-router
  stage: test
  script:
    - gradle gateway:router:test gateway:router:jacocoTestReport
    - cat gateway/router/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
