# Port of the microservice
server:
  port: 8083

spring:
  application:
    name: CONTRACT-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Secret for the JWT signing
jwt:
  secret: T2hJKTHD4D+59wwX3WG28cOD7o1haIHgYY2HaIv7XZE46bWvRDfnZBDHfSzGaDAcF/XZ+B42f2rpUE9uISN5ag==

springdoc:
  swagger-ui:
    enabled: true
